name: doumark sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  doumark:
    runs-on: ubuntu-latest
    steps:
      - name: doumark action
        uses: lizheming/doumark-action@master
        with:
          id: ${{ secrets.DOUBAN_NAME }}
          type: book
          status: mark,doing,done
          notion_token: ${{ secrets.NOTION_TOKEN }}
          args: ${{ secrets.NOTION_BOOK_URL }}
